spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/chattingroom?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Aa725386@
    driver-class-name: com.mysql.jdbc.Driver
    #    以下是数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    #    初始化大小、最大、最小连接数
    initialiSize: 5
    minIdle: 5
    maxActive: 10
    #    等待超时时间
    maxWait: 60000
    #    关闭空闲连接的间隔时间
    timeBetweenEvictionRunsMillis: 60000
    #    一个连接在一个池内的最小生存时间，单位毫秒
    minEvictableIdleTimeMills: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #    打开PSCache，并指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #    配置监控统计拦截的filters，去掉监控届满 sql 无法统计，wall 用于防火墙
    filters: stat,wall,log4j

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 130MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.anhun.entity
  config-location: classpath:mybatis-config.xml

